In [3]:
# 2.numpy属性
import numpy as np
array = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(array)
print('number of dim(维度):', array.ndim)
print('shape:', array.shape)
print('size:', array.size)

[[1 2 3]
 [4 5 6]]
number of dim(维度): 2
shape: (2, 3)
size: 6


In [4]:
# 3.array的基本用法

a = np.array([2, 3, 4, 6], dtype=np.int)  # 默认int64， int32, float64
print(a.dtype)

# arrary 
print(np.zeros((2, 2)))
print(np.ones((3, 3)))
print(np.empty((2, 3)))

print(np.arange(1, 13, 2).reshape(3, 2))  # 数列

print(np.linspace(1, 13, 6).reshape((2, 3)))  # 一条直线上取线段

int32
[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 1.   3.4  5.8]
 [ 8.2 10.6 13. ]]


In [4]:
# 5-6. 基础运算

a = np.array([1, 2, 3])
b = np.arange(1, 4)
print(a + b)
print(np.sin(a), np.cos(a), np.tan(a))
print(a < 2)
print(a**2)
# 逐个、矩阵乘法
c = a*b
c_dot = np.dot(a, b)
c_dot_2 = a.dot(b)
print(c, c_dot)
ran = np.random.random((2,3)) # 随机
print(ran, '\n', np.sum(ran, axis=1), np.max(ran, axis=0), np.min(ran, axis=1))  # axis=1 行求值， axis=0 列求值  axis用于行、列单独计算

[2 4 6]
[0.84147098 0.90929743 0.14112001] [ 0.54030231 -0.41614684 -0.9899925 ] [ 1.55740772 -2.18503986 -0.14254654]
[ True False False]
[1 4 9]
[1 4 9] 14
[[0.13453939 0.86338571 0.09488279]
 [0.80073374 0.41248989 0.80986727]] 
 [1.0928079 2.0230909] [0.80073374 0.86338571 0.80986727] [0.09488279 0.41248989]


In [86]:

print(np.argmin(a), np.argmax(a), a.mean(), np.average(a), np.median(a), a.cumsum(), np.diff(a), np.nonzero(a), np.sort(a))  # 累差，累加

# 矩阵反向
print(b.T.dot(b))
print(np.clip(a, 2, 3))  # 保留2，3之间的数

14
[2 2 3]


In [17]:
# 7. 索引
# 取行，列
aa = np.arange(3, 15).reshape(3, 4)

print(aa, aa[1][1])

print(aa[:,1:3],'\n', aa[1:3, :])# 第一列， 第1到3列 

# for循环迭代行，列
for column in aa.T:
    print(column)

print('*' * 40)
print(aa.flatten())
for item in aa.flat:
    print(item)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]] 8
[[ 4  5]
 [ 8  9]
 [12 13]] 
 [[ 7  8  9 10]
 [11 12 13 14]]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
****************************************
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [ ]:
#  8.numpy的array合并

A = np.array([1, 1, 1])
B = np.array([2, 2, 2])
print('垂直合并:\n', np.vstack((A, B)) )
print('水平合并:\n', np.hstack((A, B)) )
# print('水平合并:\t', np.hstack((A, B))

# 横向序列变为纵向序列
# print(A.T)
A = A[:,np.newaxis]
# print('改变维度：\n', A)
# 多个按维度合并
print(np.concatenate((A,A,A), axis=1))

In [ ]:
# 9.numpy的array分割

A9 = np.arange(12).reshape((3, 4))
print(A9)
# print(np.split(A9, 3 ,axis=0))
# print(np.split(A9, 2 ,axis=1))
print(np.vsplit(A9, 3))  # 水平
print(np.hsplit(A9, 2))  # 垂直

In [9]:
# 10.copy & deepcopy
a10 = np.arange(10)
b10 = a10
c10 = a10.copy()
print(a10, b10, '\na == b:', a10 is b10)
print('c is a:', a10 is c10, c10)


[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9] 
a == b: True
c is a: False [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 